export const DEFAULT_TEXTS: Record<string, string> = {
	downloadLabel: 'Download',
	attachLabel: 'Attach',
	submitLabel: 'Submit',
	chooseFileLabel: 'Choose file',
	editLabel: 'Edit',
	deleteLabel: 'Delete',
	propertyLabel: 'Properties',
	versionsLabel: 'Versions',
	viewAllLabel: 'View all...',
	deleteLastLabel: 'Delete last',
	deleteHistoryLabel: 'Delete history',
	nameLabel: 'Name: ',
	sizeLabel: 'Size: ',
	extensionLabel: 'Extension: ',
	authorLabel: 'Author: ',
	createdDateLabel: 'Create date: ',
	createdOnLabel: 'Created on',
	currentVersionLabel: 'Current version: ',
	editedByLabel: 'Edition by: ',
	okLabel: 'OK',
	yesLabel: 'Yes',
	noLabel: 'No',
	filesSubmission: 'Submission of files',
	noFileSelected: 'No file selected for submission.',
	fileSizeError: 'The selected file exceeds the allowed size of {0}.',
	extensionError: 'Invalid extension! Allowed extensions:',
	submitHeaderLabel: 'Select the file to be submitted: ',
	unlockHeaderLabel:
		'Unlock: discards the current changes and the document will be free for editing.',
	submitFilesHeaderLabel:
		'Submit: the document will be free for editing and a new version will be created.',
	majorVersionLabel: 'Major version',
	minorVersionLabel: 'Minor version',
	cancelLabelValue: 'Cancel',
	version: 'Version',
	documentLabel: 'Document',
	bytesLabel: 'Bytes',
	author: 'Author',
	deleteHeaderLabel: 'Are you sure you want to delete?',
	documentManagement: 'File Management',
	viewAll: 'View all',
	fileChoose: 'Choose a file...',
	closeLabel: 'Close',
	theLastVersionWillEliminate:
		'The last version will be eliminated.\\r\\nAre you sure you want to delete?',
	allTheVersionsExceptLastWillEliminate:
		'All the versions except the last will be deleted.\\r\\nAre you sure you want to delete?',
	uploadDocVersionHeader: 'Document versions',
	createDocument: 'Create document',
	editingDocument: 'This document is currently being edited.',
	pendingDocumentVersion: 'This document version is not yet saved.',
	errorProcessingRequest: 'An error has occurred while processing the request.'
}
