{
 "title": "Quidgest Logging",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "solution",
    "label": "Solution",
    "query": {}
   },
   {
    "name": "service",
    "label": "Service",
    "query": {}
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {}
   },
   { "name": "log_level", "label": "Log Level", "query": "Error,Warning,Info,Debug" }
  ]
 },
 "panels": [
  {
   "title": "Logs Over Time",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\r\n  count_over_time(\r\n    {service_namespace=\"$solution\", service_name=\"$service\", service_instance_id=~\"$instance\"}\r\n    | detected_level=~\"error|info|warning|debug|critical\" [$__auto]\r\n  )\r\n) by (detected_level)\r\n"
    }
   ]
  },
  {
   "title": "Top 10 error sites",
   "type": "table",
   "description": "Top 10 code sites that emitted an error",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10 , sum by (site) ( count_over_time( {service_namespace=\"$solution\"} | detected_level = \"error\" | pattern `<_> [site] <site> [` [$__auto])))"
    }
   ]
  },
  {
   "title": "Top 10 error requests",
   "type": "table",
   "description": "Request handlers of the application that were running when an error occurred inside them",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10 , sum by (ActionName) ( count_over_time({service_namespace=\"$solution\", service_name=\"$service\", service_instance_id=~\"$instance\"} | detected_level = \"error\" [$__auto])))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_namespace=\"$solution\", service_name=\"$service\", service_instance_id=~\"$instance\"} \r\n| detected_level=~\"(?i)$log_level\"",
     "maxLines": 100
    }
   ]
  }
 ]
}