//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenioServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenioServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negócio: Erro na execução de uma função..
        /// </summary>
        internal static string NegocioErroExecutarFuncao {
            get {
                return ResourceManager.GetString("Erro na execução de uma função.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha no acesso aos dados..
        /// </summary>
        internal static string Persistencia_MsgUtilizador_AcessoDados {
            get {
                return ResourceManager.GetString("Falha no acesso aos dados.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao estabelecer a ligação. .
        /// </summary>
        internal static string Persistencia_MsgUtilizador_Ligacao {
            get {
                return ResourceManager.GetString("Falha ao estabelecer a ligação.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registo não pode ser eliminado..
        /// </summary>
        internal static string Persistencia_MsgUtilizador_NaoApagar {
            get {
                return ResourceManager.GetString("O registo não pode ser eliminado porque não tem permissões suficientes.", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O registo não pode ser eliminado..
        /// </summary>
        internal static string Persistencia_MsgUtilizador_NaoApagarRel
        {
            get
            {
                return ResourceManager.GetString("O registo não pode ser eliminado porque existem registos relacionadas.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não tem permissões to change o registo. .
        /// </summary>
        internal static string Persistencia_MsgUtilizador_NaoPermissoes {
            get {
                return ResourceManager.GetString("Não tem permissões para alterar o registo.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro ao abrir a conexão: .
        /// </summary>
        internal static string PersistenciaErroAbrirConexao {
            get {
                return ResourceManager.GetString("Erro ao abrir a conexão:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro ao abrir a transacção:.
        /// </summary>
        internal static string PersistenciaErroAbrirTransaccao {
            get {
                return ResourceManager.GetString("Persistencia: Erro ao abrir a transacção:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro na função que actualiza o código interno: .
        /// </summary>
        internal static string PersistenciaErroActualizarCodInt {
            get {
                return ResourceManager.GetString("Persistencia: Erro na função que actualiza o código interno:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Excepção na alteração do registo: .
        /// </summary>
        internal static string PersistenciaErroAlterarExcepcao {
            get {
                return ResourceManager.GetString("Persistencia: Excepção na alteração do registo: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Excepção na função que conta os registos: .
        /// </summary>
        internal static string PersistenciaErroContarExcepcao {
            get {
                return ResourceManager.GetString("Persistencia: Excepção na função que conta os registos: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro na função que devolve um Qfield: .
        /// </summary>
        internal static string PersistenciaErroDevolveCampo {
            get {
                return ResourceManager.GetString("Erro na função que devolve um campo:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro na função que devolve os Qvalues das EPHs: .
        /// </summary>
        internal static string PersistenciaErroDevolveValoresEPH {
            get {
                return ResourceManager.GetString("Erro na função que devolve os valores das EPHs:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Excepção na duplicação do registo: .
        /// </summary>
        internal static string PersistenciaErroDuplicarExcepcao {
            get {
                return ResourceManager.GetString("Excepção na duplicação do registo: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: A table mãe não exists: .
        /// </summary>
        internal static string persistenciaErroDuplicarMae {
            get {
                return ResourceManager.GetString("Persistencia: A tabela mãe não existe: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Excepção na eliminação do registo:.
        /// </summary>
        internal static string PersistenciaErroEliminarExcepcao {
            get {
                return ResourceManager.GetString("Persistencia: Excepção na eliminação do registo: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro na função que elemina e insere vários registos: .
        /// </summary>
        internal static string PersistenciaErroEliminarInserirExcepcao {
            get {
                return ResourceManager.GetString("Persistencia: Erro na função que elemina e insere vários registos: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: O registo não pode ser eliminado: .
        /// </summary>
        internal static string PersistenciaErroEliminarNaoPermite {
            get {
                return ResourceManager.GetString("Persistencia: O registo não pode ser eliminado: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: O user não tem permissões to eliminate o registo..
        /// </summary>
        internal static string PersistenciaErroEliminarPermissoes {
            get {
                return ResourceManager.GetString("Persistencia: O utilizador não tem permissões para eliminar o registos.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: O registo não exists: .
        /// </summary>
        internal static string persistenciaErroEliminarRegistoInexistente {
            get {
                return ResourceManager.GetString("Persistencia: O registo não existe: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: O registo não pode ser eliminado porque existem registos associados..
        /// </summary>
        internal static string PersistenciaErroEliminarRegistosAssociados {
            get {
                return ResourceManager.GetString("Persistencia: O registo não pode ser eliminado porque existem registos associados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro na função que devolve um Qvalue: .
        /// </summary>
        internal static string PersistenciaErroExecutaEscalar {
            get {
                return ResourceManager.GetString("Persistencia: Erro na função que devolve um valor: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: O Qresult do query foi menor do que 0:.
        /// </summary>
        internal static string PersistenciaErroExecutaNonQueryResultadoInvalido {
            get {
                return ResourceManager.GetString("Persistencia: O resultado do query foi menor do que 0: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro na função que executa um query de INSERT, UPDATE ou DELETE: .
        /// </summary>
        internal static string PersistenciaErroExecutaNonReader {
            get {
                return ResourceManager.GetString("Persistencia: Erro na função que executa um query de INSERT, UPDATE ou DELETE: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro na função que devolve um DataSet:.
        /// </summary>
        internal static string PersistenciaErroExecutaReaderDataSet {
            get {
                return ResourceManager.GetString("Persistencia: Erro na função que devolve um DataSet: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro na função que devolve os registos entre duas linhas: .
        /// </summary>
        internal static string PersistenciaErroExecutaReaderEntre {
            get {
                return ResourceManager.GetString("Persistencia: Erro na função que devolve os registos entre duas linhas: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro na função que devolve uma coluna: .
        /// </summary>
        internal static string PersistenciaErroExecutaReaderUmaColuna {
            get {
                return ResourceManager.GetString("Persistencia: Erro na função que devolve uma coluna: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro na função que devolve uma linha:.
        /// </summary>
        internal static string PersistenciaErroExecutaReaderUmaLinha {
            get {
                return ResourceManager.GetString("Persistencia: Erro na função que devolve uma linha: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro na função que verifica se exists um registo &quot;filho&quot; na base de dados:.
        /// </summary>
        internal static string PersistenciaErroExisteFilha {
            get {
                return ResourceManager.GetString("Persistencia: Erro na função que verifica se existe um registo filho na base de dados: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro na função que verifica se um registo exists na base de dados: .
        /// </summary>
        internal static string PersistenciaErroExisteRegisto {
            get {
                return ResourceManager.GetString("Persistencia: Erro na função que verifica se um registo existe na base de dados: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro ao fechar a conexão:.
        /// </summary>
        internal static string PersistenciaErroFecharConexao {
            get {
                return ResourceManager.GetString("Persistencia: Erro ao fechar a conexão: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro ao fechar a transacção:.
        /// </summary>
        internal static string PersistenciaErroFecharTransaccao {
            get {
                return ResourceManager.GetString("Persistencia: Erro ao fechar a transacção: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro a gerar o número aleatório negativo: .
        /// </summary>
        internal static string PersistenciaErroGeraAleatorioNeg {
            get {
                return ResourceManager.GetString("Persistencia: Erro a gerar o número aleatório negativo: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro na criação do identifier único: .
        /// </summary>
        internal static string PersistenciaErroGetGUID {
            get {
                return ResourceManager.GetString("Persistencia: Erro na criação do identificador único: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Excepção na função que retorna a posição de um registo: .
        /// </summary>
        internal static string PersistenciaErroGetPosRegistoExcepcao {
            get {
                return ResourceManager.GetString("Persistencia: Excepção na função que retorna a posição de um registo: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro na função que devolve um registo de uma table: .
        /// </summary>
        internal static string PersistenciaErroGetRegisto {
            get {
                return ResourceManager.GetString("Persistencia: Erro na função que devolve um registo de uma tabela: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro na função que devolve todos os registos de uma table: .
        /// </summary>
        internal static string PersistenciaErroGetTodosRegistos {
            get {
                return ResourceManager.GetString("Persistencia: Erro na função que devolve todos os registos de uma tabela: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Excepção na inserção (WebService) do registo: .
        /// </summary>
        internal static string PersistenciaErroInserir_WSExcepcao {
            get {
                return ResourceManager.GetString("Persistencia: Excepção na inserção (WebService) do registo: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Excepção na inserção do registo: .
        /// </summary>
        internal static string PersistenciaErroInserirExcepcao {
            get {
                return ResourceManager.GetString("Excepção na inserção do registo.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro na inserção de vários registos: .
        /// </summary>
        internal static string PersistenciaErroInserirVariosExcepcao {
            get {
                return ResourceManager.GetString("Persistencia: Erro na inserção de vários registos:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Excepção na função obterAreaPreenchida.
        /// </summary>
        internal static string PersistenciaErroObterAreaPreenchidaExcepcao {
            get {
                return ResourceManager.GetString("Persistencia: Excepção na função obterAreaPreenchida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Excepção na função requestTabShadow.
        /// </summary>
        internal static string PersistenciaErroPedidoTabSombraExcepcao {
            get {
                return ResourceManager.GetString("Persistencia: Excepção na função pedidoTabSombra: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: O user não tem permissões to change o registo..
        /// </summary>
        internal static string PersistenciaErroPermissoesAlterar {
            get {
                return ResourceManager.GetString("Persistencia: O utilizador não tem permissões para alterar o registo.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Existe um Qfield que não tem Qvalue correspondente: .
        /// </summary>
        internal static string PersistenciaErroPreencheAreaInserir {
            get {
                return ResourceManager.GetString("Persistencia: Existe um campo que não tem valor correspondente: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: O query não devolveu Qvalues: .
        /// </summary>
        internal static string PersistenciaErroPreencheAreaSeleccionaUm {
            get {
                return ResourceManager.GetString("Persistencia: O query não devolveu valores: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro a preencher os fields carimbo na inserção: .
        /// </summary>
        internal static string PersistenciaErroPreencheCarimboIns {
            get {
                return ResourceManager.GetString("Persistencia: Erro a preencher os campos carimbo na inserção: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro no rollback da transacção: .
        /// </summary>
        internal static string PersistenciaErroRollbackTransaccao {
            get {
                return ResourceManager.GetString("Persistencia: Erro no rollback da transacção: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Excepção na seleção de registos: .
        /// </summary>
        internal static string PersistenciaErroSeleccionarExcepcao {
            get {
                return ResourceManager.GetString("Persistencia: Excepção na seleção de registos: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Excepção na seleção dos próximos registos:.
        /// </summary>
        internal static string PersistenciaErroSeleccionarMaisExcepcao {
            get {
                return ResourceManager.GetString("Persistencia: Excepção na seleção dos próximos registos: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro na função de seleção de um registo: .
        /// </summary>
        internal static string PersistenciaErroSeleccionaUmExcepcao {
            get {
                return ResourceManager.GetString("Persistencia: Erro na função de seleção de um registo: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Existe mais do que um registo nas mesmas condições .
        /// </summary>
        internal static string PersistenciaErroSeleccionaUmExisteMaisQueUm {
            get {
                return ResourceManager.GetString("Persistencia: Existe mais do que um registo nas mesmas condições.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: O registo não exists na Base de dados..
        /// </summary>
        internal static string PersistenciaErroSeleccionaUmRegistoInexistente {
            get {
                return ResourceManager.GetString("Persistencia: O registo não existe na Base de dados.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: O tipo de ligação não exists ou não está definido. .
        /// </summary>
        internal static string PersistenciaErroTipoLigacao {
            get {
                return ResourceManager.GetString("Persistencia: O tipo de ligação não existe ou não está definido.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistencia: Erro nas validações na gravação de um registo: .
        /// </summary>
        internal static string PersistenciaErroValidacoesGravacao {
            get {
                return ResourceManager.GetString("Persistencia: Erro nas validações na gravação de um registo: ", resourceCulture);
            }
        }
    }
}
