USE [W_GnBD]
ALTER INDEX ALL ON FORCITY
REBUILD;
ALTER INDEX ALL ON FORCONTACT
REBUILD;
ALTER INDEX ALL ON FORCOUNT
REBUILD;
ALTER INDEX ALL ON FORCTAX
REBUILD;
ALTER INDEX ALL ON FORPHOTO
REBUILD;
ALTER INDEX ALL ON USERLOGIN
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESS
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSARGUMENT
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONEMAILSIGNATURE
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONMESSAGE
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSATTACHMENTS
REBUILD;
ALTER INDEX ALL ON USERAUTHORIZATION
REBUILD;
ALTER INDEX ALL ON FORPROPERTY
REBUILD;
ALTER INDEX ALL ON FORAGENT
REBUILD;
GO